import './globals.css';

import { Lobster } from 'next/font/google';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const lobster = Lobster({ weight: '400', subsets: ['latin'] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main className="w-full min-h-screen flex">
          <div className="bg-stone-100 border-r border-stone-200 h-screen w-64">
            <div
              style={lobster.style}
              className="text-xl py-2 px-4 text-stone-700"
            >
              blockjam
            </div>
          </div>
          <div className="flex flex-col flex-1 h-screen">
            <div className="h-32 border-b border-stone-200 flex items-center px-4">
              Header
            </div>
            <div className="overflow-auto">
              <div className="lg:w-1/2 mx-auto pt-32 pb-96">{children}</div>
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
